# Generated by Django 5.1.1 on 2024-10-07 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreightBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('shipping_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发货日期')),
                ('origin', models.CharField(max_length=100, verbose_name='发货地')),
                ('destination', models.CharField(max_length=100, verbose_name='目的地')),
                ('calculation_address', models.CharField(max_length=255, verbose_name='计算地址')),
                ('contact_person', models.CharField(max_length=50, verbose_name='联系人')),
                ('plan_number', models.CharField(max_length=50, verbose_name='计划单号')),
                ('package_count', models.IntegerField(verbose_name='件数')),
                ('total_weight', models.FloatField(verbose_name='总重量（KG）')),
                ('total_volume', models.FloatField(verbose_name='总方数(m³）')),
                ('payment_method', models.CharField(choices=[('垫付', '垫付'), ('现付', '现付'), ('月结', '月结'), ('其他', '其他')], max_length=10, verbose_name='运费支付方式')),
                ('shipping_method', models.CharField(choices=[('零担', '零担'), ('整车', '整车')], max_length=10, verbose_name='发货方式')),
                ('pricing_method', models.CharField(choices=[('件', '件'), ('重量', '重量'), ('体积', '体积')], max_length=10, verbose_name='零担计价方式')),
                ('car_type', models.CharField(choices=[('4.2米车', '4.2米车'), ('6.8米车', '6.8米车'), ('其他', '其他')], max_length=10, verbose_name='专车车型')),
                ('is_carpool', models.BooleanField(default=False, verbose_name='是否拼车')),
                ('unit_price', models.FloatField(verbose_name='单价(元)')),
                ('amount', models.FloatField(verbose_name='金额(元)')),
                ('other_fees', models.FloatField(verbose_name='其他费用')),
                ('total_amount', models.FloatField(verbose_name='总金额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '运费账单',
                'verbose_name_plural': '运费账单',
            },
        ),
    ]
